package com.project.multi.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.project.multi.entities.Producto;


/**
 * Generated by Spring Data Generator on 12/09/2017.
 */
@Repository
public interface ProductRepository extends JpaRepository<Producto, Long> {

}
